services:
  postgres:
    image: postgres
    container_name: payt_postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - payt_network

  laravel_app:
    container_name: payt-app
    build: .
    env_file: .env
    ports:
    - 8000:8000
    networks:
      - payt_network
    depends_on:
      - postgres


volumes:
  pg:

networks:
  payt_network:
    name: payt_network
